#Base file (english)
homepage.title=Welcome to Spring Boot MVC I18n App
homepage.link1= Register Customer

registrationpage.title= Register Customer Details
registrationpage.cno=Customer Number
registrationpage.cname=Customer Name
registrationpage.addrs=Customer Addrs
registrationpage.billamount=Customer BillAmount
registrationpage.caption=Register Customer


 