spring.application.name=WishMessageMS  

#instance id
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}


# MS port number
server.port=9002

#Registers the MS with euerek server
eureka.client.service-url.default-zone=http://localhost:8761/eureka
