# MS port number
server.port=7001

# MS Application namne
spring.application.name=IPLPLAYER-SERVICE

#Instance id
eureka.instance.instance-id=${spring.application.name}:${random.value}

#register the MS with EurekaService
eureka.client.service-url.default-zone=http://localhost:8761/eureka


# specify admin server link
spring.boot.admin.client.url=http://localhost:9999/

# To  link with config server
spring.config.import=optional:configserver:


# logging  information
logging.file.name=d:/916_iplplayer_log6.txt
logging.level.com.nt=DEBUG


# Enable Circuit Breaker using  resilence4j
resilience4j.circuitbreaker.instances.Shopping-Ms.registerHealthIndicator=true
# Failure rate threshold (percentage)
resilience4j.circuitbreaker.instances.Shopping-Ms.failureRateThreshold=50
# Slow call rate threshold (percentage)
resilience4j.circuitbreaker.instances.Shopping-Ms.slowCallRateThreshold=60
# Minimum number of calls before Circuit Breaker evaluates health
resilience4j.circuitbreaker.instances.Shopping-Ms.slidingWindowSize=10
# Type of sliding window: COUNT_BASED or TIME_BASED
resilience4j.circuitbreaker.instances.Shopping-Ms.slidingWindowType=COUNT_BASED
# Time to wait before moving from OPEN to HALF-OPEN state
resilience4j.circuitbreaker.instances.Shopping-Ms.waitDurationInOpenState=20s
# Minimum number of calls required to evaluate slow call rate
resilience4j.circuitbreaker.instances.Shopping-Ms.minimumNumberOfCalls=5
# Consider calls slow if they exceed this duration
resilience4j.circuitbreaker.instances.Shopping-Ms.slowCallDurationThreshold=2s
# Maximum wait duration for permitted calls in HALF-OPEN state
resilience4j.circuitbreaker.instances.Shopping-Ms.permittedNumberOfCallsInHalfOpenState=2
# Automatic transition from OPEN to HALF-OPEN state enabled
resilience4j.circuitbreaker.instances.Shopping-Ms.automaticTransitionFromOpenToHalfOpenEnabled=true

#ACtivate the Actuators
management.endpoints.web.exposure.include=*
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true



