spring.application.name=BootMSProj13-CloudAPIGateway

# API gateway port number
server.port=9988

#  Spring Cloud API  gateway configurations
spring.cloud.gateway.routes[0].id=ShoppingMS
spring.cloud.gateway.routes[0].uri=http://localhost:6061/
spring.cloud.gateway.routes[0].predicates[0]=Path=/shopping-api/**

spring.cloud.gateway.routes[1].id=BillingMS
spring.cloud.gateway.routes[1].uri=http://localhost:9093/
spring.cloud.gateway.routes[1].predicates[0]=Path=/billing-api/**


#register  API gateway with eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Activate the actuators
management.endpoints.web.exposure.include=*




