spring.application.name=BootMSProj06-ConfigServer


#Config server port
server.port=8888

#Link  this Config server with  External Config file
spring.cloud.config.server.git.uri=https://github.com/natarazworld/NTSPBMS916Repo.git

logging.file.name=d:/ntspmbs916_elk_config.txt
logging.level.com.nt=DEBUG

