# config server port
server.port=8888

#Link  ConfigServer with GITHUB Acccount
spring.cloud.config.server.git.uri=https://github.com/natarazworld/NTSPBMS916Repo.git


#Logging configurations
logging.file.name=d:/916_configserver_log2.txt
logging.level.com.nt=DEBUG



