spring.application.name=BootMVCProj01-FirstApp


#View resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


#Embedded  Tomcat server port number
server.port=4041


#Context path of the web application (useful while using Embedded server)
server.servlet.context-path=/MVCProj01

