spring.application.name=BillingMS

# Embedded server port
server.port=9093

# instnace id 
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}

# register  with  Euraka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Connect to Config client
spring.config.import=optional:configserver:


#Activate the  actuators
management.endpoints.web.exposure.include=*



