spring.application.name=BootIOCProj10-ValueAnnotation-SPEL

#For  Course catalog
cj.price=3000
aj.price=4000
spbms.price=6000
aws.price=3000
devOps.price=3000
ui.price=2000
db.price=3000
test.price=1500

#For Traning Institute
ti.name=NIT
ti.addrs=hyd

#Custom  properties file
spring.config.import=com/nt/commons/Info.properties
