spring.application.name=BootMVCProj13-I18nApp

#Confiure the base  file
spring.messages.basename=com/nt/commons/App

#View Resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


