spring.application.name=BootDataJPAProj08-InMemoryDB


#JDBC Driver details
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:db1
spring.datasource.username=root
spring.datasource.password=root

#Hibernate - JPA details
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Embedded H2 Port number
server.port=5666
#  enable the console
spring.h2.console.enabled=true







