spring.application.name=BootDataJPAProj07-DateTime


#  DataSource cfg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///ntspbms916db
spring.datasource.username=root
spring.datasource.password=root

#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=system
#spring.datasource.password=tiger


#Hibernate - JPA properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


