spring.application.name=BootMVCProj03-SeasonApp-DataRendering



#View resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


# Embedded server port
server.port=4041
# Context Path
server.servlet.context-path=/SeasonApp

