spring.application.name=BillingMS

# Embedded server port
server.port=9093

# instnace id 
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}

# register  with  Euraka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Connect to Config client
spring.config.import=optional:configserver:


#Activate the  actuators
management.endpoints.web.exposure.include=*

# Link this  ms to  Admin Server as admin client
spring.boot.admin.client.url=http://localhost:9999


# To  get more details about  config props
management.endpoint.configprops.show-values=always
# To  get more details about  env
management.endpoint.env.show-values=always

#Activate  heap dump
management.endpoint.heapdump.access=unrestricted





#To enable  info actuator
management.info.env.enabled=true
#To activate  shudown actuator
management.endpoint.shutdown.access=unrestricted

#Logging configurations
logging.file.name=d:/ntspmbs916_elk_billingms.txt
logging.level.com.nt=DEBUG


