spring.application.name=BootJpaProj18-InteractingWithMultipleDBs


#oracle datasoruce  cfg
ora.ds.driver-class-name=oracle.jdbc.driver.OracleDriver
ora.ds.jdbc-url=jdbc:oracle:thin:@localhost:1521:xe
ora.ds.username=system
ora.ds.password=tiger

#mysql datasoruce  cfg
msql.ds.driver-class-name=com.mysql.cj.jdbc.Driver
msql.ds.jdbc-url=jdbc:mysql:///ntspbms710db
msql.ds.username=root
msql.ds.password=root


