spring.application.name=EurekaServer


# port number
server.port=8761

#Disable two  properties inherited from  parent project
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging  configurations
logging.level.com.nt=DEBUG
logging.file.name=d:/916_eurekaserver_log1.txt


