spring.application.name=BootMSProj07-ConfigServer


#Config server port
server.port=8888

# Activate native profile  to  work with  native config file
spring.profiles.active=native

# specify the location of  native  config  file
spring.cloud.config.server.native.search-locations=classpath:/config


