spring.application.name=BootIOCProj06-RealtimeDI-MinProject-LayeredApp

 #jdbc driver details
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=system
spring.datasource.password=tiger
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.url=jdbc:mysql:///ntspbms916db
