spring.application.name=BootIOCProj11BulkInjection


# college information
clg.info.cid=1001
clg.info.cname=CBIET
clg.info.addrs=hyd
clg.info.strengh=1000
clg.info.email=raja@123.com
# For array property
clg.info.favColors[0]=red
clg.info.favColors[1]=green
clg.info.favColors[2]=yellow


#clg.info.favColors=red1,green1,yellow1
# For List collection
clg.info.friends[0]=raju
clg.info.friends[1]=suresh
clg.info.friends[2]=mahesh
# For Set collection
clg.info.phones[0]=9999999
clg.info.phones[1]=8888888
clg.info.phones[2]=7777777
# For Map collection
clg.info.id-details.aadhar=4554545
clg.info.idDetails.pan=45454551
clg.info.idDetails.voterid=545454545

# For HAS-A property
clg.info.university.uid=4551
clg.info.university.uname=ICFAI
clg.info.university.uaddrs=hyd

college.email=@raja@456.com

# banner 
spring.main.banner-mode=console
