spring.application.name=BootRestProj09-DoctorAPI-MiniProject


#Embedded server port
server.port=5051

#ContextPath
server.servlet.context-path=/RestProj09


#DataSource cfg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///ntspbms916db
spring.datasource.username=root
spring.datasource.password=root

# hibernate- jpa properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


