# Ms Port number
server.port=7002

# Application name
spring.application.name=IPLTEAM-SERVICE

# Instance Id
eureka.instance.instance-id=${spring.application.name}:${random.value}

# register with  eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka


# To  activte the all actuators
management.endpoints.web.exposure.include=*
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always

# To  link MS with config server  (making the MS as the  Config Client)   (to get  all common properties from gitlab.com)
spring.config.import=optional:configserver:

# To  link  MS with admin server  (Making the MS as the Admin Client)
spring.boot.admin.client.url=http://localhost:9999/

# logging  information
logging.file.name=d:/916_iplteam_log5.txt
logging.level.com.nt=DEBUG


