spring.application.name=ShoppingMS-ConsumerMS

#Consumer  MS port
server.port=6061

#Regisgter with  eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Connect to Config client
spring.config.import=optional:configserver:

#Activate the  actuators
management.endpoints.web.exposure.include=*

#  To get  more  details from health actuator
management.endpoint.health.show-details=always
# To disble  health actuator
#management.endpoint.health.access=none

# To  get more details about  config props
management.endpoint.configprops.show-values=always
# To  get more details about  env
management.endpoint.env.show-values=always

#Activate  heap dump
management.endpoint.heapdump.access=unrestricted


logging.level.com.nt=DEBUG
logging.level.com.nt.rest=DEBUG



#To enable  info actuator
management.info.env.enabled=true
#To activate  shudown actuator
management.endpoint.shutdown.access=unrestricted

#  info about  Project
info.app.name=ShoppingMS
info.app.version=1.0
info.app.vendor=SunMS
info.app.lead=MR.RN

# changing the base path of actuator
management.endpoints.web.base-path=/mynonfiction












