spring.application.name=BootMVCProj08-RequestParamsBinding


# View Resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#Embedded server port
server.port=4041

#Context Path
server.servlet.context-path=/MVCProj01


